[package]
name = "flood_fill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"
itertools = "0.11.0"
